server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://rm-bp1iv12zo818oql20125010.mysql.rds.aliyuncs.com:3306/mogu_blog?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&serverTimezone=GMT%2B8
    #url: jdbc:mysql://rm-bp1iv12zo818oql20125010.mysql.rds.aliyuncs.com:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: zy
    password: zhangyong123##

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zy.myblog.entities    # 所有Entity别名类所在包
