server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #-------------------------直接访问服务，并且使用路由自带的负载均衡
          #uri: http://localhost:8001 #非访问集群方式
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址,访问集群，负载均衡 使用自带的负载均衡
          predicates:
            - Path=/payment/get/**
          #-------------------------直接访问服务，并且使用路由自带的负载均衡

          #--------------------访问消费端，使用带有openfeign负载均衡，远程调用的
        - id: payment_router2
          uri: http://localhost:80
          predicates:
            - Path=/feign/consumer/getpaymentbyid/**
          #--------------------访问消费端，使用带有openfeign负载均衡，远程调用的






eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka