server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 47.114.172.114:80

service-url:
  nacos-user-service: http://alibaba-provider